
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target ‘SwiftDemo‘ do
    pod 'Moya', '~> 11.0'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'SnapKit', '~> 4.0.0'
    pod 'ESTabBarController-swift'
    pod 'DeviceKit', '~> 1.3'
end

